SMPTE/ris-osvp-metadata-camdkit

src/main/python/camdkit/model.py, src/main/python/camdkit/red/cooke.py, src/main/python/camdkit/red/reader.py, src/test/python/test_cooke_data.py, src/test/python/test_red_reader.py
Closes #7 
Closes #9 
Closes #5
=> Added support for RED physical sensor dimensions, entrance pupil position and iris position

src/main/python/camdkit/arri/reader.py, src/main/python/camdkit/model.py, src/main/python/camdkit/red/reader.py, src/test/python/test_arri_reader.py, src/test/python/test_model.py, src/test/python/test_red_reader.py
=> Model: add white balance (#11)

src/main/python/camdkit/arri/reader.py, src/main/python/camdkit/model.py, src/main/python/camdkit/red/reader.py, src/main/python/camdkit/venice/reader.py, src/test/python/test_arri_reader.py, src/test/python/test_model.py, src/test/python/test_red_reader.py, src/test/python/test_venice_reader.py
=> Clarify sensor_*_dimensions

src/main/python/camdkit/arri/reader.py, src/main/python/camdkit/red/reader.py, src/main/python/camdkit/utils.py, src/main/python/camdkit/venice/reader.py, src/test/python/test_utils.py
=> Add support for approximate fractional frame rates

src/main/python/camdkit/arri/reader.py, src/main/python/camdkit/model.py, src/main/python/camdkit/red/reader.py, src/main/python/camdkit/venice/reader.py, src/test/python/test_arri_reader.py, src/test/python/test_model.py, src/test/python/test_red_reader.py, src/test/python/test_venice_reader.py
=> Rename fps to capture_fps

src/main/python/camdkit/arri/reader.py, src/main/python/camdkit/model.py, src/main/python/camdkit/red/reader.py, src/main/python/camdkit/venice/reader.py, src/test/python/test_arri_reader.py, src/test/python/test_model.py, src/test/python/test_red_reader.py, src/test/python/test_venice_reader.py
=> Remove active_sensor_pixel_dimensions

src/main/python/camdkit/framework.py, src/main/python/camdkit/model.py, src/test/python/test_model.py
=> Add support for FDL linking

src/main/python/camdkit/red/reader.py, src/test/python/test_red_reader.py
=> RED reader: fix focus distance

src/main/python/camdkit/arri/reader.py, src/main/python/camdkit/red/reader.py, src/test/python/test_arri_reader.py, src/test/python/test_red_reader.py
=> Encode focal length in mm in RED and ARRI readers

src/main/python/camdkit/canon/reader.py, src/main/python/camdkit/model.py, src/test/python/test_model.py
=> Add support for F-number

src/main/python/camdkit/arri/reader.py, src/main/python/camdkit/bmd/reader.py, src/main/python/camdkit/canon/reader.py, src/main/python/camdkit/model.py, src/main/python/camdkit/red/cooke.py, src/main/python/camdkit/red/reader.py, src/main/python/camdkit/venice/reader.py, src/test/python/test_arri_reader.py, src/test/python/test_bmd_reader.py, src/test/python/test_canon_reader.py, src/test/python/test_cooke_data.py, src/test/python/test_model.py, src/test/python/test_red_reader.py, src/test/python/test_venice_reader.py
=> Add support for camera and lens identification information

src/main/python/camdkit/model.py
=> Fixes description of entrance_pupil_position

src/main/python/camdkit/framework.py, src/test/python/test_model.py, src/tools/python/make_documentation.py
=> Fix reader coverage table in documentation

src/main/python/camdkit/framework.py, src/test/python/test_bmd_reader.py, src/test/python/test_cooke_data.py, src/test/python/test_model.py
=> Fix documentation typos

src/main/python/camdkit/framework.py, src/main/python/camdkit/model.py, src/test/python/test_framework.py
=> Fix StrictlyPositiveRationalParameter and align it with OpenEXR practice

src/main/python/camdkit/framework.py, src/main/python/camdkit/model.py, src/test/python/test_framework.py
Add Rational parameter type.
Closes #91
=> Allow the entrance pupil position to be positive or negative

src/main/python/camdkit/examples.py, src/main/python/camdkit/framework.py, src/main/python/camdkit/model.py, src/main/python/camdkit/mosys/f4.py, src/test/python/test_framework.py, src/test/python/test_model.py, src/test/python/test_mosys_reader.py
Remove first of two identical-save-comment-wording TimingMode definitions.
=> Remove first of two redundant TimingMode definitions

src/main/python/camdkit/examples.py, src/main/python/camdkit/framework.py, src/main/python/camdkit/model.py, src/test/python/test_model.py
=> Addresses various parameter issues

MIGRATION.md, src/main/python/camdkit/examples.py, src/main/python/camdkit/framework.py, src/main/python/camdkit/model.py, src/test/cpp/opentrackio-parser/opentrackio-parser/src/opentrackIOlib.cpp, src/test/cpp/opentrackio-parser/opentrackio-parser/src/opentrackIOlib.h, src/test/python/parser/opentrackio_lib.py, src/test/python/parser/opentrackio_parser.py, src/test/python/parser/opentrackio_receiver.py, src/test/python/parser/opentrackio_sender.py, src/test/python/test_model.py, src/tools/python/templates/OpenTrackIO.html
- Example sender and receiver
- Rewritten parser and library
- Changed from 'master' to 'leader' throughout
- Updated documentation with UDP header
=> Updates to v0.9.2

src/main/python/camdkit/lens_types.py, src/test/python/test_lens_types.py, src/test/resources/classic/examples/complete_dynamic_example.json, src/test/resources/classic/examples/complete_static_example.json, src/test/resources/classic/examples/recommended_dynamic_example.json, src/test/resources/classic/examples/recommended_static_example.json, src/test/resources/classic/schema.json, src/test/resources/classic/subschemas/lens.json
These were inclusive bounds, which made no sense.
=> Exclusive zero lower bound for pinhole focal length, f-number and T-stop

src/tools/python/templates/OpenTrackIO.html
This follows directly from the wikipedia article: https://en.wikipedia.org/wiki/Fletcher%27s_checksum
And matches the reference implementation in src/test/python/parser/opentrackio_lib.py
=> Update the reference implementation of fletcher-16

CHANGELOG.md, setup.cfg, src/main/python/camdkit/versioning_types.py, src/test/python/parser/README.md, src/test/python/parser/opentrackio_lib.py, src/test/python/parser/opentrackio_sender.py
Requires merge of #193 and #197
=> Bump version to 1.0.1
